"""empty message

Revision ID: 3f00879bc667
Revises: ade5ee0327d6
Create Date: 2017-06-29 09:55:18.146893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f00879bc667'
down_revision = 'ade5ee0327d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketlists')
    op.drop_table('Bucketlist Items')
    op.drop_table('Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Users_id_seq"\'::regclass)'), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('second_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'Users_pkey'),
    sa.UniqueConstraint('email', name=u'Users_email_key'),
    sa.UniqueConstraint('password_hash', name=u'Users_password_hash_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Bucketlist Items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Bucketlist Items_id_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('bucket_list_item_identifier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bucket_list_it_belongs_to', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bucket_list_it_belongs_to'], [u'bucketlists.name'], name=u'Bucketlist Items_bucket_list_it_belongs_to_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'Bucketlist Items_pkey'),
    sa.UniqueConstraint('bucket_list_it_belongs_to', name=u'Bucketlist Items_bucket_list_it_belongs_to_key')
    )
    op.create_table('bucketlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bucketlist_identifier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], [u'Users.email'], name=u'bucketlists_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'bucketlists_pkey'),
    sa.UniqueConstraint('name', name=u'bucketlists_name_key')
    )
    # ### end Alembic commands ###
